### ISSUE TITLE
File formats supported

### ISSUE THREAD

**Issue by simeon9696** [joshbuddy/exif-be-gone#14]
Hi! 

What file formats are supported with this package?

**Comment by joshbuddy** [comment]
Hi. It works on any file that has exif data in it. I think in the tests it works on .ps, .tiff and .jpg files, but I think thats not an exhaustive list of files that have exif data in them.

**Comment by xnacly** [comment]
it also works on pngs

**Comment by joshbuddy** [comment]
Oh wow, didn't realize that about PNG files. I think it might also work on WAV files too. I'm getting the impression a lot of things use exif data actually.

**Comment by joshbuddy** [comment]
I've updated the tests to check various webp and png images. Closing out this issue, but feel free to re-open if there is something else that needs to be done,
