### ISSUE TITLE
Exif in PNG gets through

### ISSUE THREAD

**Issue by dirksen-dps** [joshbuddy/exif-be-gone#26]
Here's what I did:
- I converted Canon_40D.jpg in the repo to Canon_40D.png: ![Canon_40D](https://user-images.githubusercontent.com/88202317/217665681-7456ec7a-b78c-4789-849b-ed7eea491c81.png) using the Preview app in Mac
- Scrub the file using:`npx exif-be-gone Canon_40D.png Canon_40D.cleaned.png`
- Compare the results:`diff -y <(exiftool Canon_40D.png ) <(exiftool Canon_40D.cleaned.png)`

The two results are almost the same. Particularly, the cleaned version still has all the camera-related metadata.

I expect the cleaned PNG would have the same metadata set as the cleaned JPG.

**Comment by joshbuddy** [comment]
Hey, for some reason I didn't notice this issue until right now. Sorry about that.

I've added png support here https://github.com/joshbuddy/exif-be-gone/pull/27

I'm going to merge this and deploy a new minor version. Thanks for filing this issue

**Comment by joshbuddy** [comment]
I'm going to go ahead and close this, but please re-open if there is something more.
